Python. Homework #5. Пяйве Олег.
pyaiveoleg/semester_4_python pull request #11
Opened 2021-04-08 13:17 UTC by pyaiveoleg

2021-04-09 13:38 UTC, nbirillo requested changes
Great!

2021-04-09 13:38 UTC, nbirillo commented on homeworks/homework_5/task_1/cartesian_tree.py
> +            yield from self.root
In python by default functions return None value. I think you should simplify functions and return something by default because it is a weak place and a potential place for bugs. For example:
```
if self.root is None:
    return

yield from self.root
```

2021-04-09 13:38 UTC, nbirillo commented on homeworks/homework_5/task_1/cartesian_tree.py
> +            yield from reversed(self.root)
You can simplify it:
```
if self.root is None:
    return

yield from reversed(self.root)
```

2021-04-09 13:38 UTC, nbirillo commented on homeworks/homework_5/task_1/node.py
> +        else:
You can reduce nesting by removing else

2021-04-09 13:38 UTC, nbirillo commented on homeworks/homework_5/task_1/node.py
> +        else:
You can reduce nesting by removing else

2021-04-09 13:38 UTC, nbirillo commented on tests/homework_5/task_1/test_node.py
> +            self.assertEqual(json.loads(answer_file.read(), cls=Node.NodeJSONDecoder), root)
I think you should move json loads in into a function

2021-04-09 16:45 UTC, pyaiveoleg commented on homeworks/homework_5/task_1/node.py
> +        else:
Not 153 string, 149? Isn't it?

2021-04-19 12:24 UTC, nbirillo approved these changes
Great, thanks!

2021-04-19 12:24 UTC, merged