Python. Homework #2. Task #2. Пяйве Олег.
pyaiveoleg/semester_4_python pull request #6
Opened 2021-03-11 20:58 UTC by pyaiveoleg

2021-03-12 08:31 UTC, nbirillo requested changes

2021-03-12 08:31 UTC, nbirillo commented on homeworks/homework_2/task_3/smart_args.py
> +def smart_args(function: Callable = None, positional_arguments_included: bool = False):
Please, use `*` between `function` and `positional_arguments_included`

2021-03-12 08:31 UTC, nbirillo commented on homeworks/homework_2/task_3/smart_args.py
> +        # print(a)
Should you delete it?

2021-03-12 08:31 UTC, nbirillo commented on homeworks/homework_2/task_3/smart_args.py
> +        a = inspect.getfullargspec(function)
Please, don't use too short variable names

2021-03-12 08:31 UTC, nbirillo commented on homeworks/homework_2/task_3/smart_args.py
> +def smart_args(function: Callable = None, positional_arguments_included: bool = False):
Please, fix the following case:
```
@smart_args(positional_arguments_included=True)
def support_positionals(x=Isolated(), y=5, /):
    x[0] += 1
    return (x, y)

X = [0]
print(support_positionals(X, 5))
print(support_positionals(X))
```
I got an IndexError error

2021-03-12 08:31 UTC, nbirillo commented on homeworks/homework_2/task_3/smart_args.py
> +def smart_args(function: Callable = None, positional_arguments_included: bool = False):
And this one:
```
@smart_args(positional_arguments_included=True)
def support_positionals(x, y=Evaluated(lambda:123), /):
    x[0] += 1
    return (x, y)

X = [0]
print(support_positionals(X, 5))
print(support_positionals(X))
```
I got a TypeError

2021-03-13 12:03 UTC, SpirinEgor approved these changes

2021-03-13 12:03 UTC, merged